name: 'GASNewsletter'
description: 'this actions request Gas project for send newsletter'
inputs:
  base_url:
    description: 'base url of gas project'
    required: true
  title:
    description: 'Title of newsletter'
    required: true
  subtitle:
    description: 'Subtitle of newsletter'
    required: true
  img:
    description: 'Image in newsletter'
    required: true
  updateTitle:
    description: 'Title of this update'
    required: true
  link:
    description: 'link redirect of learn more button'
    required: true
  password:
    description: 'password for access'
    required: true
outputs:
  body: # id of output
    description: 'body of response HTTP'
runs:
  using: 'node16'
  main: 'index.js'
